export default [
  {
    id: 1,
    img: "/team-images/person1.png",
    h1: "Asim Khawaja",
    position: "Lead Dev",
    p: "Lorem ipsum dolor sit amet, consectetur adipiscing elit integeriet.",
    twitter: "https://github.com/Ammara703/IceCream-Website",
    facebook: "https://github.com/Ammara703/IceCream-Website",
    linkedin: "https://github.com/Ammara703/IceCream-Website",
  },
  {
    id: 2,
    img: "/team-images/person2.png",
    h1: "Nasir Aslam",
    position: "Product Manager",
    p: "Lorem ipsum dolor sit amet, consectetur adipiscing elit integeriet.",
    twitter: "https://github.com/Ammara703/IceCream-Website",
    facebook: "https://github.com/Ammara703/IceCream-Website",
    linkedin: "https://github.com/Ammara703/IceCream-Website",
  },
  {
    id: 3,
    img: "/team-images/person3.png",
    h1: "Awais Mukhtar",
    position: "Backend Lead",
    p: "Lorem ipsum dolor sit amet, consectetur adipiscing elit integeriet.",
    twitter: "https://github.com/Ammara703/IceCream-Website",
    facebook: "https://github.com/Ammara703/IceCream-Website",
    linkedin: "https://github.com/Ammara703/IceCream-Website",
  },
  {
    id: 4,
    img: "/team-images/person4.png",
    h1: "Name",
    position: "position",
    p: "Lorem ipsum dolor sit amet, consectetur adipiscing elit integeriet.",
    twitter: "https://github.com/Ammara703/IceCream-Website",
    facebook: "https://github.com/Ammara703/IceCream-Website",
    linkedin: "https://github.com/Ammara703/IceCream-Website",
  },
];
